// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingTool.Data;

#nullable disable

namespace TicketingTool.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250109201442_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Project Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technical User",
                            NormalizedName = "TECH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TicketingTool.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4db88bf2-49e3-42d6-b859-a90675a5d893",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedUserName = "X001",
                            PasswordHash = "AQAAAAIAAYagAAAAEJGIzrhTUCqs3jKfqbqNqOyAsDeP2HewgHUCy/vqWB/ZwyXskV9mKi6B7S7jviiLvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0a483bfa-73dd-4e10-8873-fb529b851682",
                            Surname = "User",
                            TwoFactorEnabled = false,
                            UserName = "X001"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aa97153a-1574-4111-96bb-b3e312206e8e",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Ticket",
                            NormalizedUserName = "TECH01",
                            PasswordHash = "AQAAAAIAAYagAAAAECcH5ztt7b8qDPChCm3B2FFOfy10+m49BPckz0ivxsv/YQtW8uv86aLXEvoSPtMSNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b41551d3-efa0-4d70-a9d1-f3510fa8a3c8",
                            Surname = "Creator",
                            TwoFactorEnabled = false,
                            UserName = "TECH01"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fc9c75d4-4ccb-4bb1-94ed-b2c73ebc574c",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Job",
                            NormalizedUserName = "TECH02",
                            PasswordHash = "AQAAAAIAAYagAAAAEBIB/Dfv/vOY4hu/ww2tMTtE3Ma2b+sceO0U0f5r2ZObQ1nu0pd2JAT3Bjiw1FYb6g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f8e2b1b9-2465-44ea-863d-f2217fec1d9f",
                            Surname = "User",
                            TwoFactorEnabled = false,
                            UserName = "TECH02"
                        });
                });

            modelBuilder.Entity("TicketingTool.Areas.Identity.Data.ProjectUserRole", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUserRole");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            UserId = "X001",
                            RoleId = "ADMIN"
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = "TECH01",
                            RoleId = "TECH"
                        },
                        new
                        {
                            ProjectId = 1,
                            UserId = "TECH02",
                            RoleId = "TECH"
                        });
                });

            modelBuilder.Entity("TicketingTool.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorRefId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorRefId");

                    b.HasIndex("IssueKey");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TicketingTool.Models.Component", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ComponentName = "Unidentified",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 2,
                            ComponentName = "User Interface Module",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 3,
                            ComponentName = "Database Management",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 4,
                            ComponentName = "API Gateway",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 5,
                            ComponentName = "Logging Service",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 6,
                            ComponentName = "Notification System",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 7,
                            ComponentName = "Payment Processor",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 8,
                            ComponentName = "Analytics Engine",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 9,
                            ComponentName = "Reporting Tool",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 10,
                            ComponentName = "Cache Management",
                            ProjectID = 1
                        },
                        new
                        {
                            ID = 11,
                            ComponentName = "Authentication Service",
                            ProjectID = 1
                        });
                });

            modelBuilder.Entity("TicketingTool.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Counter = 5,
                            ProjectKey = "BSC",
                            ProjectName = "Basic Project"
                        });
                });

            modelBuilder.Entity("TicketingTool.Models.Status", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StatusName = "Open"
                        },
                        new
                        {
                            ID = 2,
                            StatusName = "In Progress"
                        },
                        new
                        {
                            ID = 3,
                            StatusName = "Resolved"
                        },
                        new
                        {
                            ID = 4,
                            StatusName = "Closed"
                        });
                });

            modelBuilder.Entity("TicketingTool.Models.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AssigneeID")
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ComponentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IssueKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("AssigneeID");

                    b.HasIndex("ComponentID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("IssueKey")
                        .IsUnique();

                    b.HasIndex("ProjectID");

                    b.HasIndex("StatusID");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ComponentID = 1,
                            CreatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 776, DateTimeKind.Local).AddTicks(4416),
                            CreatorID = "X001",
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Curabitur duis non dis ligula potenti praesent aenean. Mus etiam ridiculus viverra sed sapien nascetur, turpis tempor sollicitudin. Aptent enim luctus dui; urna per id. Sodales auctor vel accumsan dictumst placerat feugiat lectus curabitur? Quam risus lorem vitae commodo porttitor orci ultrices.",
                            IssueKey = "BSC-1",
                            LastUpdatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(298),
                            ProjectID = 1,
                            StatusID = 1,
                            Title = "Seed Ticket 1"
                        },
                        new
                        {
                            ID = 2,
                            ComponentID = 1,
                            CreatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(499),
                            CreatorID = "X001",
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Curabitur duis non dis ligula potenti praesent aenean. Mus etiam ridiculus viverra sed sapien nascetur, turpis tempor sollicitudin. Aptent enim luctus dui; urna per id. Sodales auctor vel accumsan dictumst placerat feugiat lectus curabitur? Quam risus lorem vitae commodo porttitor orci ultrices.",
                            IssueKey = "BSC-2",
                            LastUpdatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(502),
                            ProjectID = 1,
                            StatusID = 1,
                            Title = "Seed Ticket 2"
                        },
                        new
                        {
                            ID = 3,
                            ComponentID = 1,
                            CreatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(506),
                            CreatorID = "X001",
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Curabitur duis non dis ligula potenti praesent aenean. Mus etiam ridiculus viverra sed sapien nascetur, turpis tempor sollicitudin. Aptent enim luctus dui; urna per id. Sodales auctor vel accumsan dictumst placerat feugiat lectus curabitur? Quam risus lorem vitae commodo porttitor orci ultrices.",
                            IssueKey = "BSC-3",
                            LastUpdatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(507),
                            ProjectID = 1,
                            StatusID = 1,
                            Title = "Seed Ticket 3"
                        },
                        new
                        {
                            ID = 4,
                            ComponentID = 1,
                            CreatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(544),
                            CreatorID = "X001",
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Curabitur duis non dis ligula potenti praesent aenean. Mus etiam ridiculus viverra sed sapien nascetur, turpis tempor sollicitudin. Aptent enim luctus dui; urna per id. Sodales auctor vel accumsan dictumst placerat feugiat lectus curabitur? Quam risus lorem vitae commodo porttitor orci ultrices.",
                            IssueKey = "BSC-4",
                            LastUpdatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(546),
                            ProjectID = 1,
                            StatusID = 1,
                            Title = "Seed Ticket 4"
                        },
                        new
                        {
                            ID = 5,
                            ComponentID = 1,
                            CreatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(548),
                            CreatorID = "X001",
                            Description = "Lorem ipsum odor amet, consectetuer adipiscing elit. Curabitur duis non dis ligula potenti praesent aenean. Mus etiam ridiculus viverra sed sapien nascetur, turpis tempor sollicitudin. Aptent enim luctus dui; urna per id. Sodales auctor vel accumsan dictumst placerat feugiat lectus curabitur? Quam risus lorem vitae commodo porttitor orci ultrices.",
                            IssueKey = "BSC-5",
                            LastUpdatedDate = new DateTime(2025, 1, 9, 21, 14, 41, 778, DateTimeKind.Local).AddTicks(549),
                            ProjectID = 1,
                            StatusID = 1,
                            Title = "Seed Ticket 5"
                        });
                });

            modelBuilder.Entity("TicketingTool.Models.TicketChange", b =>
                {
                    b.Property<int>("ChangeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeID"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ChangedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("ChangeID");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("TicketID");

                    b.ToTable("TicketChange");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingTool.Areas.Identity.Data.ProjectUserRole", b =>
                {
                    b.HasOne("TicketingTool.Models.Project", "ProjectRef")
                        .WithMany("UserRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", "UserNameRef")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRef");

                    b.Navigation("UserNameRef");
                });

            modelBuilder.Entity("TicketingTool.Models.Comment", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", "AuthorRef")
                        .WithMany()
                        .HasForeignKey("AuthorRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingTool.Models.Ticket", "TicketRef")
                        .WithMany("Comments")
                        .HasForeignKey("IssueKey")
                        .HasPrincipalKey("IssueKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorRef");

                    b.Navigation("TicketRef");
                });

            modelBuilder.Entity("TicketingTool.Models.Component", b =>
                {
                    b.HasOne("TicketingTool.Models.Project", "ProjectRef")
                        .WithMany("Components")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRef");
                });

            modelBuilder.Entity("TicketingTool.Models.Ticket", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", "AssigneeRef")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssigneeID")
                        .HasPrincipalKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TicketingTool.Models.Component", "ComponentRef")
                        .WithMany()
                        .HasForeignKey("ComponentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", "CreatorRef")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatorID")
                        .HasPrincipalKey("UserName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingTool.Models.Project", "ProjectRef")
                        .WithMany("Tickets")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TicketingTool.Models.Status", "StatusRef")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssigneeRef");

                    b.Navigation("ComponentRef");

                    b.Navigation("CreatorRef");

                    b.Navigation("ProjectRef");

                    b.Navigation("StatusRef");
                });

            modelBuilder.Entity("TicketingTool.Models.TicketChange", b =>
                {
                    b.HasOne("TicketingTool.Areas.Identity.Data.ApplicationUser", "ChangedByRef")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .HasPrincipalKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingTool.Models.Ticket", "TicketRef")
                        .WithMany("Changes")
                        .HasForeignKey("TicketID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByRef");

                    b.Navigation("TicketRef");
                });

            modelBuilder.Entity("TicketingTool.Areas.Identity.Data.ApplicationUser", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("CreatedTickets");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("TicketingTool.Models.Project", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Tickets");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TicketingTool.Models.Ticket", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
